import { Skill } from '@/types/skills';

export const Skills: Skill[] = [
  {
    logo: '/HTML5.svg',
    title: 'HTML',
    firstTried: '2023-06-29',
    category: 'Frontend',
  },
  {
    logo: '/CSS3.svg',
    title: 'CSS',
    firstTried: '2023-06-05',
    category: 'Frontend',
  },
  {
    logo: '/Sass.svg',
    title: 'SCSS',
    firstTried: '2023-09-11',
    category: 'Frontend',
  },
  {
    logo: '/JavaScript.svg',
    title: 'JavaScript',
    firstTried: '2023-10-22',
    category: 'Full stack',
  },
  {
    logo: '/jQuery.svg',
    title: 'jQuery',
    firstTried: '2024-02-21',
    category: 'Frontend',
  },
  {
    logo: '/Node.js.svg',
    title: 'Node.js',
    firstTried: '2024-08-01',
    category: 'Backend',
  },
  {
    logo: '/Express.svg',
    title: 'Express',
    firstTried: '2024-09-20',
    category: 'Backend',
  },
  {
    logo: '/MongoDB.svg',
    title: 'MongoDB',
    firstTried: '2024-09-20',
    category: 'Database',
  },
  {
    logo: '/Mongoose.js.svg',
    title: 'Mongoose.js',
    firstTried: '2024-09-20',
    category: 'Backend',
  },
  {
    logo: '/TypeScript.svg',
    title: 'TypeScript',
    firstTried: '2024-12-18',
    category: 'Full stack',
  },
  {
    logo: '/Vite.js.svg',
    title: 'Vite.js',
    firstTried: '2024-12-25',
    category: 'Frontend',
  },
  {
    logo: '/React.svg',
    title: 'React',
    firstTried: '2024-12-25',
    category: 'Frontend',
  },
  {
    logo: '/Tailwind CSS.svg',
    title: 'Tailwind CSS',
    firstTried: '2025-01-08',
    category: 'Frontend',
  },
  {
    logo: '/Nest.js.svg',
    title: 'Nest.js',
    firstTried: '2025-02-09',
    category: 'Backend',
  },
  {
    logo: '/Docker.svg',
    title: 'Docker',
    firstTried: '2025-02-14',
    category: 'Devops',
  },
  {
    logo: '/218346783-72be5ae3-b953-4dd7-b239-788a882fdad6.svg',
    title: 'Zustand',
    firstTried: '2025-02-20',
    category: 'Frontend',
  },
  {
    logo: '/Redis.svg',
    title: 'Redis',
    firstTried: '2025-03-20',
    category: 'Database',
  },
  {
    logo: '/Next.js.svg',
    title: 'Next.js',
    firstTried: '2025-04-03',
    category: 'Fullstack-framework',
  },
  {
    logo: '/PostgresSQL.svg',
    title: 'PostgresSQL',
    firstTried: '2025-05-15',
    category: 'Database',
  },
  {
    logo: '/108468352.png',
    title: 'Drizzle',
    firstTried: '2025-05-15',
    category: 'Backend',
  },
  {
    logo: '/GraphQL.svg',
    title: 'GraphQL',
    firstTried: '2025-05-18',
    category: 'Full stack',
  },
  {
    logo: '/apollo-graphql-compact.svg',
    title: 'Apollo',
    firstTried: '2025-05-18',
    category: 'Full stack',
  },
  {
    logo: '/1_amx8k-Upat1L7RzluiMcow.png',
    title: 'NX',
    firstTried: '2025-05-25',
    category: 'Devops',
  },
  {
    logo: '/Fastify.svg',
    title: 'Fastify',
    firstTried: '2025-06-21',
    category: 'Backend',
  },
  {
    logo: '/RabbitMQ.svg',
    title: 'RabbitMQ',
    firstTried: '2025-06-05',
    category: 'Message-broker',
  },
  {
    logo: '/Yarn.svg',
    title: 'Yarn',
    firstTried: '2025-02-09',
    category: 'Tool',
  },
  {
    logo: '/Bun.svg',
    title: 'Bun',
    firstTried: '2025-04-03',
    category: 'Tool',
  },
  {
    logo: '/GitHub.svg',
    title: 'GitHub',
    firstTried: '2023-10-26',
    category: 'Tool',
  },
  {
    logo: '/Git.svg',
    title: 'Git',
    firstTried: '2025-02-09',
    category: 'Tool',
  },
  {
    logo: '/Swagger.svg',
    title: 'Swagger',
    firstTried: '2025-02-29',
    category: 'Tool',
  },
  {
    logo: '/1_elhu-42TzQEdsFjKDbQhhA.png',
    title: 'React Query',
    firstTried: '2025-02-20',
    category: 'Frontend',
  },
  {
    logo: '/passport.svg',
    title: 'Passport JS',
    firstTried: '2024-11-28',
    category: 'Backend',
  },
  {
    logo: '/1_O-ClkORJkmUm1wRsApB_yQ.png',
    title: 'Shadcn',
    firstTried: '2025-04-13',
    category: 'Frontend',
  },
  {
    logo: '/Telegram_logo.svg.webp',
    title: 'Telegram bot API',
    firstTried: '2024-10-03',
    category: 'Backend',
  },
  {
    logo: '/Telegram_logo.svg.webp',
    title: 'Telegram Web App',
    firstTried: '2025-05-21',
    category: 'Frontend',
  },
];
