import type { Metadata } from 'next';
import './globals.css';
import { Montserrat } from 'next/font/google';
import Header from '@/components/shared/Header';
import { Providers } from '@/providers/providers';

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-montserrat',
  display: 'swap',
});

export const metadata: Metadata = {
  icons: '/Maksym_Zhuk.svg',
  title: 'Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${montserrat.className} antialiased`}>
        <Providers>
          <div className="w-full min-h-[100dvh] bg-[#171717]">
            <Header />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
